### ISSUE TITLE
dependency not resolving from bintray pluginRepository 

### ISSUE THREAD

**Issue by manfredk** [gantsign/kotlin-maven-plugin-tools#262]
Hi,

just fyi - I followed the readme to declare bintray as plugin repository, but maven had issues resolving the dependency and was showing the error:

    Could not find artifact com.github.gantsign.maven.plugin-tools:kotlin-maven-plugin-tools:pom:0.9.9 in central (https://repo.maven.apache.org/maven2)

It turned out, that additionally declaring the repo location as `repository` (not just `pluginRepository`) solved the issue:

    <repositories>
        <repository>
            <id>bintray-gantsign-maven</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/gantsign/maven/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>bintray-gantsign-maven</id>
            <name>bintray-plugins</name>
            <url>https://dl.bintray.com/gantsign/maven/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

**Comment by freemanjp** [comment]
Did you add `com.github.gantsign.maven.plugin-tools:kotlin-maven-plugin-tools` to the project dependencies instead of (or as well as) the `maven-plugin-plugin` plugin dependencies? `pluginRepository` is for plugins and their dependencies, `repositories` is for project dependencies.

The dependency should only be under the plugin i.e.:
```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-plugin-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
          <extractors>
            <extractor>kotlin</extractor>
          </extractors>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.github.gantsign.maven.plugin-tools</groupId>
            <artifactId>kotlin-maven-plugin-tools</artifactId>
            <version>0.9.24</version>
          </dependency>
        </dependencies>
      </plugin>
```

**Comment by manfredk** [comment]
yes, i was adding it to the project dependencies as well. When following your advice maven downloads dependencies and compiles successfully (`mvn clean compile`) , but IntelliJ still complains in the pom about not finding v0.9.24.

Having problems with the maven-plugin-plugin not discovering the annotations in my kotlin plugin code was my initial motivation to use the kotlin-maven-plugin-tools. 

Unfortunately, when doing a mvn clean install which is also running my goal in the generate-sources phase, i got a `KotlinNullPointerException` from the descriptor goal. This is the output (_full stacktrace available_):
```
$ mvn clean install -X -e
. . .
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.6.0:descriptor (default-
descriptor) on project gorky-maven-plugin: Execution default-descriptor of goal org.apache.maven.plugi
ns:maven-plugin-plugin:3.6.0:descriptor failed.: KotlinNullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugin
s:maven-plugin-plugin:3.6.0:descriptor (default-descriptor) on project gorky-maven-plugin: Execution d
efault-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.6.0:descriptor failed.
```


That is the reason, why I removed the references to your plugin and instead investigated, how you get the annotations discovered in your plugin's kotlin code - and created a primary constructor for my mojo, annotated with @Inject (javax.inject).

**Comment by freemanjp** [comment]
Hi, @manfredk. I've finally reimplemented the Kotlin source scanning (Dokka replaced with Kotlin compiler) and deployed the new version (`1.0.0`) to Maven Central. I suspect it may fix the above issue.
