### ISSUE TITLE
compiling my plugin fails because of different versioned kotlin runtime wrapped in dokka embeddable

### ISSUE THREAD

**Issue by manfredk** [gantsign/kotlin-maven-plugin-tools#263]
Hi, 

I'm using version 0.9.9 of the plugin-tools in my plugin project. Compiling (with `mvn clean install`) fails because of a different versioned kotlin runtime wrapped in the dokka embeddable. This is the error message:

```
[INFO] --- maven-plugin-plugin:3.6.0:helpmojo (help-goal) @ gorky-maven-plugin ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[ERROR] warning: some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a di
fferent version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
[ERROR] C:\Users\...\.m2\repository\com\github\gantsign\maven\plugin-tools\dokka-embeddable\0.9.9\dokka-embeddable-0.9.9.jar: warning: library has Kotlin
 runtime bundled into it
[ERROR] warning: some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a di
fferent version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
[ERROR] C:\Users\...\.m2\repository\com\github\gantsign\maven\plugin-tools\dokka-embeddable\0.9.9\dokka-embeddable-0.9.9.jar: warning: library has Kotlin
 runtime bundled into it
[ERROR] warning: some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a di
fferent version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
[ERROR] C:\Users\...\.m2\repository\com\github\gantsign\maven\plugin-tools\dokka-embeddable\0.9.9\dokka-embeddable-0.9.9.jar: warning: library has Kotlin
 runtime bundled into it
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Any idea, how to solve this?

**Comment by freemanjp** [comment]
Is there some reason you're using version `0.9.9` (it's almost two years old - `0.9.24` is the latest version)?

Can you run `mvn -X plugin:helpmojo` and add a comment with the output.

**Comment by manfredk** [comment]
the reason is that i get rather confused at times with version listings and pick the latest version as if it be sorted numerically.
Since the prev post above, I removed the plugin and cannot reproduce the issue above any more, sorry.

**Comment by Chris-Frendo** [comment]
Hi,

I have a similar issue related to the bundled dokka dependencies. 

I am using the version 0.9.26 (latest as of writing this comment) and my project uses the latest kotlin version (1.6.10). After some digging I found that the plugin is using dokka version 0.10.1 (released over a year ago). The latest version of dokka is 1.6.10, which supports kotlin 1.6.10 (which I think would solve my problem). 

https://github.com/Kotlin/dokka/releases/tag/v1.6.10

Are there any plans on upgrading the dokka version sometime soon?
