### ISSUE TITLE
Bintray will be shut down, any plans on moving to Maven Central?

### ISSUE THREAD

**Issue by petertrr** [gantsign/kotlin-maven-plugin-tools#293]
Bintray will be shut down soon, and Github Code Quality action already reports `https://dl.bintray.com/gantsign/maven` as well as `https://jcenter.bintray.com/` as a soon-to-be-deprecated repository. So I was wondering if there are any plans to deploy the library to Maven Central and can we expect a new release in the nearest future?

**Comment by freemanjp** [comment]
The problem I have is `org.jetbrains.dokka:dokka-fatjar`, it's not available on Maven Central. I partially convert it to a skinny jar so it works better with Maven (https://github.com/gantsign/kotlin-maven-plugin-tools/tree/master/dokka-embeddable). But there's still various dependencies mixed in under various licenses (in some cases I've had trouble identifying licenses - JetBrains appears to have forked some of the dependencies). To deploy to Maven Central I have to declare the licence for each artifact, which I can't accurately do for `dokka-embeddable`. 

There are a couple of solutions to this:

* The easiest one is to move the artifact from BinTray to GitHub. I expect this will be the short term solution.
* I think the latest Dokka version has a skinny JAR I can use. But, Dokka has undergone significant refactoring and it's going to take a significant effort for this project to migrate to the new version (These APIs were never really intended for use outside Dokka). Frankly, I haven't had time. Assuming there's a skinny jar I can use, and assuming Dokka is deployed to Maven Central, I should be able to deploy this to Maven Central, it just may be a while until I find the time.

**Comment by petertrr** [comment]
Thanks for reply and for explanation! Your reasons are understandable. Moving to github packages seems like a reasonable solution  that at least won't break existing pipelines in dependent projects. I might try to look into helping with API migration myself, but I as well can't be sure about the free time.

**Comment by freemanjp** [comment]
@petertrr as of version [0.9.26](https://github.com/gantsign/kotlin-maven-plugin-tools/releases/tag/0.9.26) new releases are now deployed to GitHub Packages, note that authentication is required to download from GitHub Packages (any valid GitHub token will do) - details in the README.

**Comment by petertrr** [comment]
Thanks @freemanjp! I've switched to the new version in our project, it works good. We use `kotlin-maven-plugin-tools` only in release maven profile, so I only needed to add authentication in our CI job, and using `GITHUB_TOKEN` is fairly straightforward.

**Comment by marcelmay** [comment]
@freemanjp  : `org.jetbrains.dokka:dokka-fatjar` seems now available on Maven Central: https://repo1.maven.org/maven2/org/jetbrains/dokka/dokka-fatjar/
