### ISSUE TITLE
Make artifacts available on Jitpack

### ISSUE THREAD

**Issue by ledoyen** [gantsign/kotlin-maven-plugin-tools#326]
Hi,

Thanks you for contributing this, it helps a lot.

Could you think that you can make the artifacts available from JitPack ?

Right now JitPack requires authentication to downlad these binaries meaning there should be some configuration to do on you side in the JitPack administration.

To be honest, GitHub packages is very painfull to use (when it works).
I understand that publishing to Maven Central is a long task, but it should be pretty straightforward to make it available from JitPack and is a very decent alternative to Central when it comes to tooling.

**Comment by freemanjp** [comment]
Hi, @ledoyen. I've finally reimplemented the Kotlin source scanning (Dokka replaced with Kotlin compiler) and deployed the new version (`1.0.0`) to Maven Central.

**Comment by ledoyen** [comment]
Many thanks !
